### PR TITLE
Build fixes and support hi3518ev100 build

### LINKED ISSUE #1126: unable to access sdcard / mmc on hi3518ev100 from openipc uboot
after flashing my ipcam (jovision h210?), unit boots fine, but I'm unable to do anything with mmc (sdcard) via fatload/fatinfo in uboot
`fatinfo mmc` gives:
```
** Invalid boot device **
```
initial flashing w/ fatload worked fine from original uboot, & mmc/sdcard also works fine in openipc linux

serial console log:
```
U-Boot 2010.06 (Nov 14 2022 - 19:25:39)

Check spi flash controller v350... Found
Spi(cs1) ID: 0xEF 0x40 0x17 0x00 0x00 0x00
Spi(cs1): Block:64KB Chip:8MB Name:"W25Q64FV"
In:    serial
Out:   serial
Err:   serial
RAM size: 64MB
Hit any key to stop autoboot:  0 
OpenIPC # 
OpenIPC # fatinfo mmc

** Invalid boot device **
OpenIPC # version

U-Boot 2010.06 (Nov 14 2022 - 19:25:39)
OpenIPC # getinfo
getinfo - print hardware information

Usage:
getinfo bootmode - get start memeory type e.g. nand/spi etc
getinfo nand - get nand flash information
getinfo spi - get spi flash information
getinfo version - get system version

OpenIPC # getinfo version
version: 3.0.3
OpenIPC # 
```

ipctool output from original image:
```
# ./ipctool 
Error: unexpected value for SOI == 0x9711
---
chip:
  vendor: HiSilicon
  model: 3518EV100
board:
  possible-IR-cut-GPIO: 6,18,20,42,43,44,73,76,79
ethernet:
  mac: "3c:33:00:c2:7d:19"
  u-mdio-phyaddr: 1
  phy-id: 0x0000ffff
  d-mdio-phyaddr: 0
  phy-mode: mii
rom:
- type: nor
  block: 64K
  partitions:
    - name: boot
      size: 0x40000
      sha1: 867356df
      contains:
        - name: uboot-env
          offset: 0x30000
    - name: appfs
      size: 0x480000
      path: /home,squashfs
      sha1: 36e885c9
    - name: ker
      size: 0x1b0000
      sha1: 2502100d
    - name: rootfs
      size: 0x100000
      sha1: f61bac71
    - name: hwconfig
      size: 0x10000
      sha1: 3becb626
    - name: config
      size: 0x80000
      path: /etc/ppp,jffs2,rw
    - name: flash
      size: 0x800000
      sha1: 37a108d6
  size: 16M
  addr-mode: 3-byte
ram:
  total: 64M
  media: 21M
firmware:
  u-boot: "2010.06 (Jul 31 2015 - 17:02:35)"
  kernel: "3.0.8 (Mon Jun 29 11:56:43 CST 2015)"
  toolchain: gcc version 4.4.1 (Hisilicon_v100(gcc4.4-290+uclibc_0.9.32.1+eabi+linuxpthread)) 
  libc: uClibc 0.9.32.1
  sdk: "Hi3518_MPP_V1.0.A.1  (Aug 24 2015, 22:43:01)"
  main-app: /tmp/sctrl
sensors:
- vendor: OmniVision
  model: OV9712
  control:
    bus: 0
    type: i2c
    addr: 0x60
  data:
    type: DC
  clock: 24MHz
# 
```

### PR DESCRIPTION
**Pull request by zerog2k**
fixes https://github.com/OpenIPC/firmware/issues/1126

### CODE REVIEW

**Review by flyrouter — COMMENTED** [review]
Thank you very much for your suggestions.
We will consider them as soon as possible.

**Comment by flyrouter** [comment]
On this repository @dimerr makes the final decision, we will wait for his information.

**Comment by flyrouter** [comment]
At the moment, we compile bootloaders only with native compilers from the SDK since there are many unsolvable problems, and the device is quite old. The system environment of the manufacturer's standard compiler contains all the necessary scripts and files.


```
SOC=hi3518e


for SOC in hi3518a hi3518c hi3518e hi3516c; do
#make ARCH=arm CROSS_COMPILE=arm-hisiv100nptl-linux- distclean
make ARCH=arm CROSS_COMPILE=arm-hisiv100nptl-linux- clean
make ARCH=arm CROSS_COMPILE=arm-hisiv100nptl-linux- ${SOC}_config
make ARCH=arm CROSS_COMPILE=arm-hisiv100nptl-linux- -j12 || exit 1

#make mini-boot.bin
#cp mini-boot.bin ~/src/hisi/uboot/u-boot-${SOC}v100-universal.bin

../../tools/pc_tools/uboot_tools/mkboot.sh reg_info_${SOC}.bin u-boot-${SOC}.bin

cp u-boot-${SOC}.bin ~/src/hisi/uboot/u-boot-${SOC}v100-universal.bin

done
```

**Comment by zerog2k** [comment]
interesting. @viktorxda pointed to this for building
https://github.com/OpenIPC/distributor
which is where i got this approach from
(patching old uboot for, and building with modern toolchains; as well as these other uboot repos having facility inside of their makefiles for those cpus handling the special hisilicon uboot header patching)

It is completely functional, and now has the missing sdcard/mmc code/tooling:
```
Requesting system reboot


U-Boot 2010.06 (Nov 16 2023 - 09:35:51)

Check spi flash controller v350... Found
Spi(cs1) ID: 0xEF 0x40 0x17 0x00 0x00 0x00
Spi(cs1): Block:64KB Chip:8MB Name:"W25Q64FV"
MMC:   MID:0x27 RBlock:512 WBlock:512 Chip:29508MB Name:"SD32G"
SD:   Ver:2.0 High Capacity Speed:25000000Hz Bus Width:4bit
In:    serial
Out:   serial
Err:   serial
RAM size: 64MB
Interface:  MMC
  Device 0: Vendor: Man 275048 Snr c9130407 Rev: 6.0 Prod: SD32G
            Type: Removable Hard Disk
            Capacity: 29508.0 MB = 28.8 GB (60432384 x 512)
Partition 1: Filesystem: FAT32 "UNTITLED   "
reading u-boot
reading kernel
reading rootfs
USB:   scanning bus for devices... 2 USB Device(s) found
0 Storage Device(s) found
Hit any key to stop autoboot:  0 
OpenIPC # mmcinfo
Device: HIMCI_V100
Manufacturer ID: 27
OEM: 5048
Name: SD32G 
Tran Speed: 25000000
Rd Block Len: 512
SD version 2.0
High Capacity: Yes
Capacity: 30941380608
Bus Width: 4-bit
OpenIPC # 
OpenIPC # fatls mmc 0
            .spotlight-v100/
            .fseventsd/
   182580   u-boot-hi3518ev100-universal.bin 
  6816747   openipc.hi3518ev100-nor-lite.tgz 
  4902912   rootfs.squashfs 
  1925424   uimage 
            rtl8188eu-old/
  4902912   rootfs.squashfs.hi3518ev100 
  1925420   uimage.hi3518ev100 
            .trash-1000/

6 file(s), 4 dir(s)

```

I could convert this to a patch which a standalone build script (like `build-hi3518e.sh`) can apply before building, so that the repo still can be built externally with old toolchain. Alternatively, maybe the old master (for old toolchain) could be put on a separate frozen branch, e.g. `legacy`, for that purpose. Was thinking here that folks who want to build their own version of the uboot (with modern toolchain) can. But whatever the team/maintainers think is best, we can do it.

**Comment by flyrouter** [comment]
Please note that the Distributor system is designed to compile loaders and gradually test and migrate features. 
We cannot simply apply a patch or update U-Boot without all the necessary tests on the entire line of processors. The PR sent to you is a great honor, thank you of course, however the solution and discussions will be done in a workflow. i.e. not so fast, please expect.

Note that the current bootloaders were going to 2020. If we change the compiler later, e.g. by updating Buildroot, then the loader may not change for the better and we may break something. For us now stability is important first of all. Thank you for your understanding. That's why I leave this PR open for discussion.

https://github.com/OpenIPC/firmware/releases

**Comment by viktorxda** [comment]
@zerog2k 
I added a patch to [distributor](https://github.com/OpenIPC/distributor/releases/tag/latest) based on your commits, please check if the release binaries are working correctly.

**Comment by zerog2k** [comment]
Thanks @viktorxda  & @FlyRouter 
the distributor build is working great, including mmc/sdcard support, and has the necessary scripts/info to build locally if necessary.
I'll close this PR out.

**Pull request closed without merging**
